<?php

//首页展示

Route::get('/',"IndexController@index3");
//房源分类展示
Route::get('/index',"IndexController@classindex");
//注册页面
Route::get('/reg',"IndexController@register");
//登陆页面
Route::get('/login',"IndexController@login");
//房源详情页
Route::get('/housing',"IndexController@housing");
//头像
Route::get('/headportrait','IndexController@headportrait');
//三级联动
Route::get('/regs',"IndexController@regs");
//用户登陆
Route::post('/logins',"LoginController@logins");
//用户推出
Route::get('/tui',"LoginController@tui");
//个人中心
Route::get('/users','UserController@index');
//个人信息
Route::get('/userList','UserController@userList');
//注册验证昵称的唯一性
Route::post('/nickname','RegController@nickname');
//注册
Route::post('/useradd','RegController@userAdd');
//订单管理
Route::get('/orderList','UserController@orderList');
//房客个人中心
Route::get('/usersList','UserController@usersList');
//房源管理
Route::get('/housingList','UserController@housingList');
//房客订单管理
Route::get('/OrderManagement','UserController@OrderManagement');
//房客订单取消
Route::get('/CancelOrder','UserController@CancelOrder');
//我的收藏
Route::get('/collection','UserController@collection');
//删除收藏
Route::get('/collectDel','UserController@collectDel');
//房源删除
Route::get('/houseDel','UserController@houseDel');
